### ISSUE TITLE
ფონტები გადასატანია ისე, რომ ჯინჯამ შეძლოს მათი დანახვა

### ISSUE THREAD

**Issue by davidunilab** [UnilabEdu/QartNLPWebService#71]
მაგალითად შეიძლება ფონტების მითითება head განყოფილებაში.

**Comment by temurchichua** [comment]
ეს ცადე?
https://stackoverflow.com/questions/32582644/how-to-add-custom-font-in-python-flask

**Comment by davidunilab** [comment]
პრინციპში არ ვიცი როგორ, მაგრამ ახლა რომ ჩავხედე მუშაობს. 
სავარაუდოდ ჯერჯერობით აღარც შევეხები 😄
